version: '3.8'

services:
  rpg-game:
    build: .
    container_name: old-dragon-rpg-game
    stdin_open: true
    tty: true
    volumes:
      - ./database:/app/database
      - ./logs:/app/logs
    environment:
      - TERM=xterm-256color
    restart: unless-stopped

