version: '3.8'

services:
  expo-rpg:
    build: .
    container_name: old-dragon-rpg
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    tty: true
    stdin_open: true
